import { ICategory } from "@/types/types";

import { IProduct } from "@/types/product";

export const categoryList: ICategory[] = [
  { path: "sharikovye", name: "Шариковые", img: "ball-bearings.jpg" },
  { path: "rolikovye", name: "Роликовые", img: "roller-bearings.jpg" },
  { path: "igolchatye", name: "Игольчатые", img: "needle-shaped.jpg" },
  { path: "sharnirnye", name: "Шарнирные", img: "articulated.jpg" },
  { path: "korpusnye-uzly", name: "Корпусные", img: "housing.jpg" },
  {
    path: "razemnye-korpusa",
    name: "Разъёмные корпуса",
    img: "detachable-housings.jpg",
  },
  { path: "odnoryadnye", name: "Однорядные", img: "single-row.jpg" },
  { path: "dvuhryadnye", name: "Двухрядные", img: "double-row.jpg" },
  { path: "chetyrekhryadnye", name: "Четырехрядные", img: "four-row.jpg" },
  { path: "sfericheskie", name: "Сферические", img: "spherical.jpg" },
  { path: "konicheskie", name: "Конические", img: "conical.jpg" },
  {
    path: "samoustanavlivayuschiesya",
    name: "Самоустанавливающиеся",
    img: "self-installing.jpg",
  },
  { path: "radialnye", name: "Радиальные", img: "radial.jpg" },
  {
    path: "radialno-upornye",
    name: "Радиально-упорные",
    img: "radial-thrust.jpg",
  },
  { path: "upornye", name: "Упорные", img: "persistent.jpg" },
  { path: "otkrytye", name: "Открытые", img: "open.jpg" },
  { path: "zakrytye", name: "Закрытые", img: "close.jpg" },
];

export const products: IProduct[] = [
  {
    name: "Подшипник 214",
    title: "Подшипник 214 - Купить в СПБ",
    description: "Описание подшипника 214",
    price: 349,
    article: "П0000037478",
    img: "ball-bearings.jpg",
    images: [
      "spherical.jpg",
      "conical.jpg",
      "open.jpg",
      "persistent.jpg",
      "double-row.jpg",
    ],
    characteristic: [
      { key: "Стандарт", value: "ГОСТ" },
      { key: "Бренд", value: "РВЗ" },
      { key: "Внутренний диаметр (мм)", value: 17 },
      { key: "Внешний диаметр (мм)", value: 190 },
      { key: "Ширина (мм)", value: 16.05 },
    ],
    inStock: true,
    stock: 370,
  },
  {
    name: "Подшипник 3614",
    title: "Подшипник 3614 - Купить в СПБ",
    description: "Описание подшипника 3614",
    price: 0,
    article: "00-00016908",
    img: "spherical.jpg",
    inStock: false,
    stock: 0,
  },
  {
    name: "Подшипник 67512",
    title: "Подшипник 67512 - Купить в СПБ",
    description: "Описание подшипника 67512",
    price: 600,
    article: "П0000054947",
    img: "conical.jpg",
    inStock: true,
    stock: 700,
  },
  {
    name: "Подшипник 309",
    title: "Подшипник 309 - Купить в СПБ",
    description: "Описание подшипника 309",
    price: 260,
    article: "П0000042145",
    img: "open.jpg",
    inStock: true,
    stock: 0,
  },
  {
    name: "Подшипник 8210",
    title: "Подшипник 8210 - Купить в СПБ",
    description: "Описание подшипника 8210",
    price: 160,
    article: "00-00016901",
    img: "persistent.jpg",
    inStock: true,
    stock: 180,
  },
  {
    name: "Подшипник 214",
    title: "Подшипник 214 - Купить в СПБ",
    description: "Описание подшипника 214",
    price: 349,
    article: "П0000037499",
    img: "ball-bearings.jpg",
    inStock: true,
    stock: 370,
  },
  {
    name: "Подшипник 3614",
    title: "Подшипник 3614 - Купить в СПБ",
    description: "Описание подшипника 3614",
    price: 0,
    article: "00-00016998",
    img: "spherical.jpg",
    inStock: false,
    stock: 0,
  },
  {
    name: "Подшипник 67512",
    title: "Подшипник 67512 - Купить в СПБ",
    description: "Описание подшипника 67512",
    price: 600,
    article: "П0000054911",
    img: "conical.jpg",
    inStock: true,
    stock: 700,
  },
  {
    name: "Подшипник 309",
    title: "Подшипник 309 - Купить в СПБ",
    description: "Описание подшипника 309",
    price: 260,
    article: "П0000042112",
    img: "open.jpg",
    inStock: true,
    stock: 0,
  },
  {
    name: "Подшипник 8210",
    title: "Подшипник 8210 - Купить в СПБ",
    description: "Описание подшипника 8210",
    price: 160,
    article: "00-00016913",
    img: "persistent.jpg",
    inStock: true,
    stock: 180,
  },
  {
    name: "Подшипник 3614",
    title: "Подшипник 3614 - Купить в СПБ",
    description: "Описание подшипника 3614",
    price: 0,
    article: "00-00016914",
    img: "spherical.jpg",
    inStock: false,
    stock: 0,
  },
  {
    name: "Подшипник 67512",
    title: "Подшипник 67512 - Купить в СПБ",
    description: "Описание подшипника 67512",
    price: 600,
    article: "П0000054915",
    img: "conical.jpg",
    inStock: true,
    stock: 700,
  },
];
