export interface IBearing {
  id: number;
  id1c: string;
  id1cRvz: string;
  price: number;
  priceRvz: number;
  quantity: number;
  quantityRvz: number;
  name: string;
  url: string;
  title: string;
  h1: string;
  description: string;
  group: string;
  for_img: string;
  brand: string;
  analog: string;
  analogUrl: string;
  images: string[];
  content: string;
  innerDiameter: number;
  outerDiameter: number;
  widthBearing: number;
  weight: string;
  new_product: boolean;
  stock: number;
  popular: boolean;
  bearing_for_corpus: string;
  corpus: string;
  series: string;
  bushing: string;
  bearingDesignId: number;
  bearingSealId: number;
  bearingTypeId: number;
  cornerId: number;
  feature2Id: number;
  featureId: number;
  holeId: number;
  innerRingId: number;
  loadTypeId: number;
  materialId: number;
  outerRingId: number;
  rollerTypeId: number;
  rowCountId: number;
  sealId: number;
  sepId: number;
  standartId: number;
  bushingTypeId: number;
  lubricationHoleId: number;
  connectionId: number;
  size?: string;
}

// export interface IBearing2 {
//   id: number;
//   id1c: string | null;
//   id1cRvz: string | null;
//   price: number | null;
//   priceRvz: number | null;
//   quantity: number | null;
//   quantityRvz: number | null;
//   name: string;
//   url: string;
//   title: string;
//   h1: string;
//   description: string | null;
//   brand: string;
//   analog: string;
//   analogUrl: string;
//   images: string;
//   content: string;
//   innerDiameter: number;
//   outerDiameter: number;
//   widthBearing: number;
//   newBearing: boolean;
//   stockBearing: number | null;
//   popularBearing: boolean;
//   standartId: number;
//   bodyId: number;
//   formaId: number | null;
//   loadId: number;
//   rowId: number;
//   openId: number;
// }
