export interface IServicesPages {
  path: string;
  name: string;
}

export const servicesPages: Array<IServicesPages> = [
  { path: "/about", name: "О компании" },
  { path: "/brand-rvz", name: "Бренд РВЗ" },
  { path: "/contacts", name: "Контакты" },
  { path: "/delivery", name: "Доставка и оплата" },
  { path: "/vacancy", name: "Вакансии" },
  // { path: "/catalog", name: "Каталог" },
  // { path: "/cart", name: "Корзина" },
];

export const shopPages: IServicesPages[] = [
  { path: "", name: "Главная" },
  { path: "catalog", name: "Каталог" },
  { path: "sfericheskie", name: "Сферические" },
  { path: "samoustanavlivayuschiesya", name: "Самоустанавливающиеся" },
  { path: "about", name: "О компании" },
  { path: "brand-rvz", name: "Бренд РВЗ" },
  { path: "contacts", name: "Контакты" },
  { path: "delivery", name: "Доставка и оплата" },
  { path: "vacancy", name: "Вакансии" },
  { path: "cart", name: "Корзина" },
  { path: "dvuhryadnye", name: "Двухрядные" },
  { path: "gost", name: "ГОСТ" },
  { path: "igolchatye", name: "Игольчатые" },
  { path: "iso", name: "ISO" },
  { path: "korpusnye-uzly", name: "Корпусные узлы" },
  { path: "odnoryadnye", name: "Однорядные" },
  { path: "otkrytye", name: "Открытые" },
  { path: "radialno-upornye", name: "Радиально-упорные" },
  { path: "radialnye", name: "Радиальные" },
  { path: "razemnye-korpusa", name: "Разборные корпуса" },
  { path: "rolikovye", name: "Роликовые" },
  { path: "sharikovye", name: "Шариковые" },
  { path: "sharnirnye", name: "Шарнирные" },
  { path: "upornye", name: "Упорные" },
  { path: "zakrytye", name: "Закрытые" },
  { path: "chetyrehryadnye-otkrytye", name: "Четырехрядные открытые" },
  {
    path: "chetyrehryadnye-radialno-upornye",
    name: "Четырехрядные радиально упорные",
  },
  { path: "dvuhryadnye-otkrytye", name: "Двухрядные открытые" },
  {
    path: "dvuhryadnye-radialno-upornye",
    name: "Двухрядные радиально-упорные",
  },
  { path: "dvuhryadnye-zakrytye", name: "Двухрядные закрытые" },
  { path: "gost-chetyrehryadnye", name: "ГОСТ Четырехрядные" },
  { path: "gost-dvuhryadnye", name: "ГОСТ Двухрядные" },
  { path: "gost-igolchatye", name: "ГОСТ Игольчатые" },
  { path: "gost-konicheskie", name: "Конические" },
  { path: "gost-korpusnyeuzly", name: "ГОСТ Корпусные узлы" },
  { path: "gost-odnoryadnye", name: "ГОСТ Однорядные" },
  { path: "gost-otkrytye", name: "Открытые" },
  { path: "gost-radialno-upornye", name: "ГОСТ Радиально-упорные" },
  { path: "gost-radialnye", name: "ГОСТ Радиальные" },
  { path: "gost-rolikovye", name: "ГОСТ Роликовые" },
  { path: "gost-samoustanavlivayushchiesya", name: "Самоустанавливающиеся" },
  { path: "gost-sfericheskie", name: "ГОСТ Сферические" },
  { path: "gost-sharikovye", name: "ГОСТ Шариковые" },
  { path: "gost-sharnirnye", name: "ГОСТ Шарнирные" },
  { path: "gost-upornye", name: "ГОСТ Упорные" },
  { path: "gost-zakrytye", name: "ГОСТ Закрытые" },
  { path: "igolchatye-dvuhryadnye", name: "Игольчатые Двухрядные" },
  { path: "igolchatye-odnoryadnye", name: "Игольчатые Однорядные" },
  { path: "igolchatye-otkrytye", name: "Игольчатые Открытые" },
  { path: "igolchatye-radialno-upornye", name: "Игольчатые Радиально-упорные" },
  { path: "igolchatye-radialnye", name: "Игольчатые Радиальные" },
  { path: "igolchatye-upornye", name: "Игольчатые Упорные" },
  { path: "igolchatye-zakrytye", name: "Игольчатые Закрытые" },
  { path: "iso-chetyrehryadnye", name: "ISO Четырехрядные" },
  { path: "iso-dvuhryadnye", name: "ISO Двухрядные" },
  { path: "iso-igolchatye", name: "ISO Игольчатые" },
  { path: "iso-konicheskie", name: "ISO Конические" },
  { path: "iso-odnoryadnye", name: "ISO Однорядные" },
  { path: "iso-otkrytye", name: "ISO Открытые" },
  { path: "iso-radialno-upornye", name: "ISO Радиально-упорные" },
  { path: "iso-radialnye", name: "ISO Радиальные" },
  { path: "iso-rolikovye", name: "ISO Роликовые" },
  { path: "iso-sfericheskie", name: "ISO Сферические" },
  { path: "iso-sharikovye", name: "ISO Шариковые" },
  { path: "iso-sharnirnye", name: "Шарнирные" },
  { path: "iso-upornye", name: "ISO Упорные" },
  { path: "iso-zakrytye", name: "ISO Закрытые" },
  { path: "konicheskie", name: "Конические" },
  { path: "konicheskie-dvuhryadnye", name: "Конические Двухрядные" },
  { path: "konicheskie-odnoryadnye", name: "Конические Однорядные" },
  {
    path: "konicheskie-radialno-upornye",
    name: "Конические Радиально-упорные",
  },
  { path: "odnoryadnye-otkrytye", name: "Однорядные Открытые" },
  {
    path: "odnoryadnye-radialno-upornye",
    name: "Однорядные Радиально-упорные",
  },
  { path: "odnoryadnye-zakrytye", name: "Однорядные Закрытые" },
  {
    path: "radialno-upornye-dvuhryadnye",
    name: "Радиально-упорные Двухрядные",
  },
  {
    path: "radialno-upornye-odnoryadnye",
    name: "Радиально-упорные Однорядные",
  },
  { path: "radialno-upornye-otkrytye", name: "Радиально-упорные Открытые" },
  { path: "radialno-upornye-zakrytye", name: "Радиально-упорные Закрытые" },
  { path: "radialnye-chetyrehryadnye", name: "Радиальные Четырехрядные" },
  { path: "radialnye-dvuhryadnye", name: "Радиальные Двухрядные" },
  { path: "radialnye-odnoryadnye", name: "Радиальные Однорядные" },
  { path: "radialnye-otkrytye", name: "Радиальные открыте" },
  { path: "radialnye-zakrytye", name: "Радиальные Закрытые" },
  { path: "rolikovye-chetyrehryadnye", name: "Роликовые Четырехрядные" },
  { path: "rolikovye-dvuhryadnye", name: "Роликовые Двухрядные" },
  { path: "rolikovye-odnoryadnye", name: "Роликовые Однорядные" },
  { path: "rolikovye-otkrytye", name: "Роликовые Открытые" },
  { path: "rolikovye-radialno-upornye", name: "Роликовые Радиально-упорные" },
  { path: "rolikovye-radialnye", name: "Роликовые Радиальные" },
  { path: "rolikovye-sfericheskie", name: "Роликовые Сферические" },
  { path: "rolikovye-upornye", name: "РоликовыеУпорные" },
  { path: "rolikovye-zakrytye", name: "Роликовые Закрытые" },
  { path: "samoustanavlivayushchiesya", name: "Самоустанавливающиеся" },
  { path: "sfericheskie-dvuhryadnye", name: "Сферические Двухрядные" },
  { path: "sfericheskie-odnoryadnye", name: "Сферические Однорядные" },
  { path: "sharikovye-dvuhryadnye", name: "Шариковые Двухрядные" },
  { path: "sharikovye-odnoryadnye", name: "Шариковые Однорядные" },
  { path: "sharikovye-otkrytye", name: "Шариковые Открытые" },
  { path: "sharikovye-radialno-upornye", name: "Шариковые Радиально-упорные" },
  { path: "sharikovye-radialnye", name: "Шариковые Радиальные" },
  { path: "sharikovye-upornye", name: "Шариковые упорные" },
  { path: "sharikovye-zakrytye", name: "Закрытые Шариковые" },
  { path: "sharnirnye-odnoryadnye", name: "Шарнирные однорядные" },
  { path: "upornye-dvuhryadnye", name: "Упорные Двухрядные" },
  { path: "upornye-odnoryadnye", name: "Упорные Однорядные" },
];
