import { TopNav, Header, Footer, YandexMetrika } from "@/components";
import type { Metadata } from "next";
import { ClientProvider } from "./ClientProvider/ClientProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Подшипники РВЗ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <link rel="preload" as="image" href="/slide-up.avif" fetchPriority="high" />
      </head>
      <ClientProvider>
        <body>
          <TopNav />
          <Header />
          <main>{children}</main>
          <Footer />
          <YandexMetrika />
        </body>
      </ClientProvider>
    </html>
  );
}
