import { TopNav, Header, Footer, YandexMetrika } from "@/components";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClientProvider } from "./ClientProvider/ClientProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Подшипники РВЗ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        {/* preload изображения LCP – это разрешено и полезно */}
        <link rel="preload" as="image" href="/slide-up.avif" fetchPriority="high" />
        {/* preconnect для сторонних ресурсов */}
        <link rel="preconnect" href="https://mc.yandex.ru" />
        <link rel="preconnect" href="https://mc.yandex.com" />
      </head>
      <ClientProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <TopNav />
          <Header />
          <main>{children}</main>
          <Footer />
          <YandexMetrika />
        </body>
      </ClientProvider>
    </html>
  );
}
